version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven"
      - mvn --version
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - mvn clean
  build:
    commands:
      - echo "Building Spring Boot application"
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - target/*.jar